### ISSUE TITLE
Cannot upload quantitative biological data (*.csv) file

### ISSUE THREAD

**Issue by trikaloudis** [mmzdouc/FERMO#1]
Hello, many thanks for sharing FERMO.
I have a problem uploading this .csv file (the other files are ok).
The error I get is seen below.
Many thanks for your help.
Tri

Traceback (most recent call last):
  File "C:\Users\trika\miniconda3\envs\FERMO\lib\site-packages\pandas\core\indexes\base.py", line 3803, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 2263, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 2273, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

KeyError: 0

**Comment by mmzdouc** [comment]
Hi Tri, 

thank you for trying out FERMO! 
May I take a look at the .csv-file that gives you the error when loading it into FERMO?
If you do not feel confortable posting it publicly, you can send it to my university email address: mitja.zdouc(a)wur.nl
My guess is that the pandas module (which is used to read the csv files) encounters something unexpected and throws the error, but I would have to see the file to be sure.

Kind regards, 

Mitja

**Comment by mmzdouc** [comment]
Error was due to gaps in input
