### ISSUE TITLE
Callback error updating ..store_processing.data...processed_data_FERMO.data..

### ISSUE THREAD

**Issue by nici7** [mmzdouc/FERMO#24]
Hi Mitja,

During processing my data in FERMO including MS2Query, the following error occured:

Traceback (most recent call last):
  File "C:\Users\thomenu\AppData\Local\miniconda3\envs\FERMO\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\thomenu\AppData\Local\miniconda3\envs\FERMO\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\thomenu\AppData\Local\miniconda3\envs\FERMO\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\thomenu\AppData\Local\miniconda3\envs\FERMO\lib\site-packages\dash\_callback.py", line 422, in add_context
    raise LongCallbackError(
dash.exceptions.LongCallbackError: An error occurred inside a long callback: 'NoneType' object has no attribute 'query_spectrum'
Traceback (most recent call last):
  File "C:\Users\thomenu\AppData\Local\miniconda3\envs\FERMO\lib\site-packages\dash\long_callback\managers\diskcache_manager.py", line 175, in run
    user_callback_output = fn(*maybe_progress, *user_callback_args)
  File "C:\Users\thomenu\Desktop\FERMO-main\src\fermo\app.py", line 364, in app_peaktable_processing
    FERMO_data = peaktable_processing(uploaded_files, dict_params,)
  File "C:\Users\thomenu\Desktop\FERMO-main\src\fermo\app_utils\FERMO_peaktable_processing.py", line 301, in peaktable_processing
    feature_dicts = ms2query_search(
  File "C:\Users\thomenu\Desktop\FERMO-main\src\fermo\processing\ms2query_search.py", line 160, in ms2query_search
    feature_ID = results_table.query_spectrum.get('id')
AttributeError: 'NoneType' object has no attribute 'query_spectrum'

------
The error does not occur if I process the exemple data. But I did not find differences in the table format or mgf file (only that the latter also includes the row MERGED_STATS= )
The processing of my data without MS2Query works fine.

Thank you!
Nicola

**Comment by mmzdouc** [comment]
Hi Nicola, 

thanks for your interest in FERMO! 

The error seems to be related to the generation of the MS2 spectra that are used for MS2Query matching. I haven't seen this error before. It is interesting that it only occurrs during MS2Query maching. I assume that you also did the molecular network/spectral similarity network analysis? This also uses the MS2 spectra, so it is curious that it did not break before. 

I would need some additional information to troubleshoot the error:
- The version of FERMO you have used. This you can find in the `pyprojecet.toml` file, under `[project]` and `version`
- The version of MZmine you have used. For the latest release of FERMO (version 0.8.11), we have tested until MZmine 3.4.
- Could you copy-paste the first 30-40 lines of your MGF file in this thread? The MERGED_STATS could indeed be the thing that causes the problem. 

Kind regards, 

Mitja

**Comment by nici7** [comment]
Hi,
Thanks for your fast reply! 
Yes, the creation of the molecular networks in FERMO did work.
- FERMO version = "0.8.11"
- I used MZmine 3.9.0 to create the input files. I can try version 3.4 instead. 
- Please find below some lines of the MGF file:

BEGIN IONS
FEATURE_ID=1208
PEPMASS=139.9879
SCANS=1208
RTINSECONDS=677.18
CHARGE=0+
MSLEVEL=2
140.0578 2.0E2
END IONS

BEGIN IONS
FEATURE_ID=95
PEPMASS=143.0815
SCANS=95
RTINSECONDS=161.096
CHARGE=0+
MSLEVEL=2
MERGED_STATS=1 / 2 (0 removed due to low quality, 1 removed due to low cosine).
102.0130 4.2E2
115.0861 5.3E2
END IONS

BEGIN IONS
FEATURE_ID=1794
PEPMASS=144.9820
SCANS=1794
RTINSECONDS=790.615
CHARGE=0+
MSLEVEL=2
MERGED_STATS=14 / 14 (0 removed due to low quality, 0 removed due to low cosine).
102.8896 4.8E2
103.9553 5.1E5
104.0221 4.9E2
104.0257 1.8E3
104.1936 5.2E2
121.9653 4.2E3
144.9831 8.8E2
145.0802 1.5E3
END IONS

Thanks!
Best regards,
Nicola

**Comment by mmzdouc** [comment]
Not applicable in version >=1.0.0
