### ISSUE TITLE
Error downloading MS2Query files

### ISSUE THREAD

**Issue by Dmente92** [mmzdouc/FERMO#25]
Hello,
I am trying to run Fermo v0.8.11 with MS2Query On, but it gives me the following error when downloading the files:

Callback error updating ..store_processing.data...processed_data_FERMO.data.

Traceback (most recent call last):
  File "C:\Users\dmendez\Miniconda3\envs\FERMO_v0.8.11\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dmendez\Miniconda3\envs\FERMO_v0.8.11\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\dmendez\Miniconda3\envs\FERMO_v0.8.11\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\dmendez\Miniconda3\envs\FERMO_v0.8.11\lib\site-packages\dash\_callback.py", line 422, in add_context
    raise LongCallbackError(
dash.exceptions.LongCallbackError: An error occurred inside a long callback: Multiple files could be the file containing the ms2ds_model file
Traceback (most recent call last):
  File "C:\Users\dmendez\Miniconda3\envs\FERMO_v0.8.11\lib\site-packages\dash\long_callback\managers\diskcache_manager.py", line 175, in run
    user_callback_output = fn(*maybe_progress, *user_callback_args)
  File "C:\Users\dmendez\Desktop\FERMO\src\fermo\app.py", line 364, in app_peaktable_processing
    FERMO_data = peaktable_processing(uploaded_files, dict_params,)
  File "C:\Users\dmendez\Desktop\FERMO\src\fermo\app_utils\FERMO_peaktable_processing.py", line 301, in peaktable_processing
    feature_dicts = ms2query_search(
  File "C:\Users\dmendez\Desktop\FERMO\src\fermo\processing\ms2query_search.py", line 149, in ms2query_search
    ms2library = create_library_object_from_one_dir(
  File "C:\Users\dmendez\Miniconda3\envs\FERMO_v0.8.11\lib\site-packages\ms2query\ms2library.py", line 507, in create_library_object_from_one_dir
    dict_with_file_names = select_files_for_ms2query(files_in_directory)
  File "C:\Users\dmendez\Miniconda3\envs\FERMO_v0.8.11\lib\site-packages\ms2query\ms2library.py", line 473, in select_files_for_ms2query
    assert dict_with_file_names[file_type] is None, \
AssertionError: Multiple files could be the file containing the ms2ds_model file.

I tried downloading the files by myself and copy it to the "libraries" folder, but I get the same error.

Any help would be appreciate. And thanks in advance.

**Comment by mmzdouc** [comment]
This issue is most likely caused due to changes in the MS2Query library files download, possibly related to https://github.com/mmzdouc/FERMO/issues/24.

This issue has been addressed in the upcoming version 1.0 of FERMO

**Comment by mmzdouc** [comment]
Not applicable in version >=1.0.0
