### ISSUE TITLE
installation issue: ModuleNotFoundError: No module named 'matchms.metadata_utils'

### ISSUE THREAD

**Issue by mariannaiorio** [mmzdouc/FERMO#4]
(FERMO) C:\Users\Marianna\Downloads\FERMO\FERMO-main\FERMO-main>python ./src/fermo/app.py
Traceback (most recent call last):
  File "./src/fermo/app.py", line 45, in <module>
    from app_utils.FERMO_peaktable_processing import (
  File "C:\Users\Marianna\Downloads\FERMO\FERMO-main\FERMO-main\src\fermo\app_utils\FERMO_peaktable_processing.py", line 17, in <module>
    from processing.ms2query_search import ms2query_search
  File "C:\Users\Marianna\Downloads\FERMO\FERMO-main\FERMO-main\src\fermo\processing\ms2query_search.py", line 1, in <module>
    from ms2query.run_ms2query import download_zenodo_files
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\ms2query\__init__.py", line 3, in <module>
    from .library_files_creator import LibraryFilesCreator
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\ms2query\library_files_creator.py", line 8, in <module>
    from matchmsextras.pubchem_lookup import pubchem_metadata_lookup
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\matchmsextras\pubchem_lookup.py", line 5, in <module>
    from matchms.metadata_utils import is_valid_inchikey
ModuleNotFoundError: No module named 'matchms.metadata_utils'

**Comment by mmzdouc** [comment]
Dear Marianna, 

see my response in [this Issue](https://github.com/mmzdouc/FERMO/issues/5). 

Kind regards, 

Mitja
