### ISSUE TITLE
Installation Problem on version 0.8.8 - ModuleNotFoundError: No module named 'matchms.metadata_utils'

### ISSUE THREAD

**Issue by Androx0** [mmzdouc/FERMO#5]
Ciao Mitja, thanks for sharing FERMO!
I'm having a problem during the installation procedure of the 0.8.8 version. I have tried to install both via script and manually but I keep getting the error (see log below). I went back to install the 0.5 version and everything goes smooth via script (see attachment). 
Marianna and Matteo are facing the same problem both on Mac and Windows.

Thanks for the help!
Andrea

Looking for miniconda3 in C:\Users\Dell-NAI-3\ or anaconda3 in C:\Users\Dell-NAI-3\ was successful. Proceeding ...
Attempting to activate conda environment FERMO
FERMO successfully activated.
Traceback (most recent call last):
  File "src\fermo\app.py", line 45, in <module>
    from app_utils.FERMO_peaktable_processing import (
  File "C:\Users\Dell-NAI-3\Desktop\FERMO-main\src\fermo\app_utils\FERMO_peaktable_processing.py", line 17, in <module>
    from processing.ms2query_search import ms2query_search
  File "C:\Users\Dell-NAI-3\Desktop\FERMO-main\src\fermo\processing\ms2query_search.py", line 1, in <module>
    from ms2query.run_ms2query import download_zenodo_files
  File "C:\Users\Dell-NAI-3\miniconda3\envs\FERMO\lib\site-packages\ms2query\__init__.py", line 3, in <module>
    from .library_files_creator import LibraryFilesCreator
  File "C:\Users\Dell-NAI-3\miniconda3\envs\FERMO\lib\site-packages\ms2query\library_files_creator.py", line 8, in <module>
    from matchmsextras.pubchem_lookup import pubchem_metadata_lookup
  File "C:\Users\Dell-NAI-3\miniconda3\envs\FERMO\lib\site-packages\matchmsextras\pubchem_lookup.py", line 5, in <module>
    from matchms.metadata_utils import is_valid_inchikey
ModuleNotFoundError: No module named 'matchms.metadata_utils'
Press any key to continue . . .

![FERMO](https://user-images.githubusercontent.com/117812376/218069758-55ed29d1-95d2-4b25-9ad6-81ece6b4a130.png)

**Comment by mariannaiorio** [comment]
Thank you Mitjia! Now it works!

**Comment by Androx0** [comment]
Thanks Mitja! It works!
