### ISSUE TITLE
Callback error updating ..store_processing.data...processed_data_FERMO.data..

### ISSUE THREAD

**Issue by mariannaiorio** [mmzdouc/FERMO#7]
Hi Mitjia!
During the processing of my data the following error occurred:

Traceback (most recent call last):
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\dash\dash.py", line 1274, in dispatch
    ctx.run(
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\dash\_callback.py", line 422, in add_context
    raise LongCallbackError(
dash.exceptions.LongCallbackError: An error occurred inside a long callback: 'NoneType' object has no attribute 'peaks'
Traceback (most recent call last):
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\dash\long_callback\managers\diskcache_manager.py", line 175, in run
    user_callback_output = fn(*maybe_progress, *user_callback_args)
  File "C:\Users\Marianna\Downloads\FERMO\FERMO-main\FERMO-main\src\fermo\app.py", line 364, in app_peaktable_processing
    FERMO_data = peaktable_processing(uploaded_files, dict_params,)
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\fermo\app_utils\FERMO_peaktable_processing.py", line 280, in peaktable_processing
    feature_dicts = library_search(
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\fermo\processing\library_search.py", line 79, in library_search
    scores = matchms.calculate_scores(
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\matchms\calculate_scores.py", line 62, in calculate_scores
    return Scores(references=references, queries=queries,
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\deprecated\classic.py", line 285, in wrapper_function
    return wrapped_(*args_, **kwargs_)
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\matchms\Scores.py", line 125, in calculate
    self._scores = self.similarity_function.matrix(self.references,
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\matchms\similarity\BaseSimilarity.py", line 67, in matrix
    scores[i_ref][i_query] = self.pair(reference, query)
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\matchms\similarity\ModifiedCosine.py", line 131, in pair
    spec1 = reference.peaks.to_numpy
AttributeError: 'NoneType' object has no attribute 'peaks'

**Comment by mmzdouc** [comment]
Hi Marianna!

Thanks for reporting the error! 

It looks like there is a problem with the spectral library searching module (`library_search.py`). 

Is your spectral library file in the correct (`.mgf`) format? You can also open your spectral library in a text editor and compare it to the example file in our [Spectral library preparation tutorial](https://github.com/mmzdouc/FERMO/wiki/Spectral-library-preparation-tutorial) to check if the format is correct.

If that does not help you to solve the error, you can send me your library file to mitja.zdouc (a) wur.nl and I will give it a look!

Kind regards, 

Mitja

**Comment by mariannaiorio** [comment]
Hi Mitjia, 
you were right! I had "PrecursorMz" instead of "PEPMASS" in my library. By replacing all it perfectly worked!
Thank you,
Marianna
