### ISSUE TITLE
 Callback error updating featureinfo_out.data

### ISSUE THREAD

**Issue by mariannaiorio** [mmzdouc/FERMO#8]
Hi Mitjia,
sorry for being annoying...
I received another error by analyzing the data selecting "SPEC.+TREND" and focusing on one network:

Traceback (most recent call last):
  File "C:\Users\Marianna\Downloads\FERMO\FERMO-main\FERMO-main\src\fermo\app.py", line 1484, in update_selected_feature
    return modify_feature_info_df(
  File "C:\Users\Marianna\anaconda3\envs\FERMO\lib\site-packages\fermo\app_utils\dashboard_functions.py", line 1282, in modify_feature_info_df
    str(sample_stats['original_bioactivity'][sample]), ' (',
KeyError: '17411.mzML'

Thanks for your help!

**Comment by mmzdouc** [comment]
Hi Marianna, 

no, you are not annoying at all! Quite the contrary - thank you very much for the bug report! 

The reason for the `KeyError`  was an unconsidered conditional in `dashboard_functions.py`, which was not caught during initial testing. 

The issue was fixed in the latest release [0.8.10](https://github.com/mmzdouc/FERMO/releases/tag/0.8.10).
